Fix cba fixes
SachaOropeza/AH64D-Project pull request #104
Opened 2020-12-17 17:42 UTC by Ollieollieolllie

Opening fcr from ase page
radar max detection
disabling rocket salvo to prevent bug
added vanilla thermal sensor
increased size of fixed wing cscope icons
fixed bindable jammer toggle
made ase scripts functions
made jammer activation linked to both seats
fixed tsd & FCR ADA icons
sumbunitions activation are now a function

2020-12-19 11:21 UTC, SachaOropeza commented
Again, please be more explicit on your commit titles and descriptions. Could you elaborate the "added vanilla thermal sensor" feature ?

2020-12-20 19:44 UTC, Ollieollieolllie commented
> Again, please be more explicit on your commit titles and descriptions. Could you elaborate the "added vanilla thermal sensor" feature ?

yes more specifically affects the non radar apache as currently the ARma 3 sensor only has visual and the radar but visual sensor is ineffective at night as it doesn't take into account the thermal camera on the apache this is adding the exivilant of the thermal camera to the vanila sensor that is liked to the camera for left/rigth/up/down movement

2021-01-24 17:39 UTC, SachaOropeza commented
I let @mattysmith22 review it before merging.

2021-02-02 15:36 UTC, SachaOropeza commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/event/fn_eventInit.sqf
> +    _heli setVariable ["fza_ah64_agmode", , true];
Isn't there an error ?

2021-02-02 17:50 UTC, mattysmith22 requested changes
Looks good, thank you for your help. I do have a few changes 

It has a lot of areas where I am not fully sure what the end goal was so I have asked for some clarification. If you can explain those areas of your code to me (marked in the review) then that would be great!

Also needs the same level of testing as I mentioned in the review of #98

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/CfgFunctions.hpp
> +		class Ase
Small niggle, I have been writing the categories and function names in lower case, do you mind fixing both that and the [camelCase](https://en.wikipedia.org/wiki/Camel_case)?

E.g. : 
* `Ase` -> `ase`
* `Asejammer` -> `aseJammer`
* `Aseflaredeploy` `aseFlareDeploy`

The relevant capitalisation needs to be fixed in the folder and file names for these functions too.

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/cfgSounds.hpp
> +		sound[] = {"\fza_ah64_us\audio\pnvs_fail_1.ogg",4,1,1};
I'm not well versed in `CfgSounds`, this is just a volume change right? And if so, what was the issue that this is fixing? Just want to know before I approve

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/config/sensor_b2e.hpp
> +      class IRSensorComponent: SensorTemplateIR {
What does this addition allow for?

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/XEH_clientInit.sqf
> -	CALL_ENSURE_IN_APACHE(fza_fnc_controlHandleJammersToggle)
Good fix, thank you!

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/ASE/fn_AseFlaredeploy.sqf
> +_fza_ah64_incominghandled2 = _hostile getVariable ["fza_ah64_shotCounter2", 0];
Prefix not required on local variables, only on global ones.

Change `_fza_ah64_incominghandled2` to `_counter` or similar

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/controlHandlers/fn_controlHandlelasechange.sqf
> +Function: fza_fnc_controlHandlelasechange
Broken capitalization in name (`fza_fnc_controlHandlelasechange` -> `fza_fnc_controlHandleLaseChange`.) Because it didn't have camel case I couldn't work out without reading the comments whether you had misspelled "control handle ASE change" or written "control handle lase change"

Needs fixing in CfgFunctions, file name and calls too

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/event/fn_eventFired.sqf
> +/*
If this was what's breaking the salvos, just delete it. Don't comment out unless it's only very temporary

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/event/fn_eventGetOut.sqf
> +_heli setVariable ["fza_ah64_ihadssoff", 1];
Lines 39 and 40 are just equivalent of saying 
```sqf
_heli setVariable ["fza_ah64_ihadssoff", 0];
```

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/event/fn_eventInit.sqf
> -    _heli animate["pdoor", 1];
This doesn't actually fix the initialisation issue, just makes the initialisation issue close the doors rather than open them.

Another alternative to the way we do it would be to maybe remove the use of the `fza_ah64_aircraftInitialised` variable, and just instead run it only if the script is running on a machine that [`isServer`](https://community.bistudio.com/wiki/isServer) as there is always one and only one server on the mission, even in singleplayer! Your machine is marked (`isServer`)

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdRASEDraw.sqf
> +fza_ah64_asethreatsdraw = fza_ah64_targetlist; {
What is the difference between `fza_ah64_asethreats` and `fza_ah64_asethreatsdraw` meant to be?

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdRFCRDraw.sqf
> +	_adaunit = false;
What is wrong with `fza_fnc_targetIsADA`?

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdRTSDDraw.sqf
> +		_adaunit = false;
What is wrong with fza_fnc_targetIsADA?

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/targeting/fn_targetingSched.sqf
> -    ! (((_heli getVariable "fza_ah64_agmode" == 1 && getpos _x select 2 < 10) || (_theta > 45 && _theta < 315) || (_heli getVariable "fza_ah64_agmode" == 0 && getpos _x select 2 > 10) || (((_heli dis
Why was this range increased?

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/targeting/fn_targetingUpdate.sqf
> -	if ((_heli == assignedTarget _x || _x AimedAtTarget[_heli] > 0.5) && (alive _x) && !(_x in fza_ah64_threattracking)) then {
The hope was that we could move all the stuff from page_ase into this function - I am trying to get rid of all of those schedule scripts like `page_ase`. Try to move the stuff from that script into here rather than from here to that script

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/targeting/fn_targetingSched.sqf
> +        fza_ah64_dispfcrlist - alldead;
Indentation needs tabbing out one more

2021-02-02 17:50 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/rocket_salvo.sqf
>  _salvo = _heli getVariable "fza_ah64_rocketsalvo";
Add it as a github issue please

2021-02-24 21:22 UTC, mattysmith22 requested changes
It's getting there, still not formatted correctly though. If you want I will go on a call with you and peer program the formatting with you

2021-02-24 21:22 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/event/fn_eventInit.sqf
> +    _heli setVariable ["fza_ah64_rfjon", 0, true];
Everything after line 55 needs to stay out of the init only one section

2021-02-24 21:22 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdLWPNHandleControl.sqf
> +			[_heli] spawn fza_fnc_controlHandlelaserchange;
`call`, not `spawn` preferably from a performance standpoint

2021-02-24 21:22 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdRASEDraw.sqf
> +	if (_className == "192Rnd_CMFlareMagazine" && _turretPath isEqualTo [-1]) then {
?

2021-02-24 21:22 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/page_ase.sqf
> +    fza_ah64_asethreats = vehicles - allDead; {
Need to improve performance, don't run through the massive `vehicles` array every 0.3 seconds

2021-03-14 00:06 UTC, mattysmith22 requested changes
Good job, will fix all last required fixes in a live session with you

2021-03-14 00:06 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/ASE/fn_AseFlaredeploy.sqf
> +    deploys flare if ir jam enables on ase
Capitalise D, as well as `IR jam enables on ASE`

2021-03-14 00:06 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/ASE/fn_AseFlaredeploy.sqf
> +    _this spawn fza_fnc_AseFlaredeploy;
Lower case 'a' on ase

2021-03-14 00:06 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/ASE/fn_Asejammer.sqf
> +/* ----------------------------------------------------------------------------
Function name shouldn't be capitalised, `fn_aseJammer.sqf`

2021-03-14 00:33 UTC, mattysmith22 approved these changes

2021-03-14 10:25 UTC, merged

2021-03-14 10:25 UTC, SachaOropeza commented
Good job guys !