FIX
SachaOropeza/AH64D-Project pull request #86
Opened 2020-10-25 04:19 UTC by Ollieollieolllie

FIX for ECM Script
changed 30mm to the newer ballistics computer
Re-added ADA datebase
Re-added correct auto hover detector
tempory fix for the TSD/FCR Radar Icons
Re-added missile datebase
fixed the position issue for the gunner seat engine 1 fire button
Fixed the broken shadow on the FCR

2020-10-26 22:33 UTC, mattysmith22 requested changes
I like some of the changes, thank you for reintegrating CMSmk2.sqf. However, I have some issues but have provided comments explaining where there are some areas for improvement.

Also, do you mind changing the title of the PR to something more informative like "CBA compact fix set", and copy the commit changes into the description too. It will just help me when it comes to looking at these details in the future.

2020-10-26 22:33 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdRFCRDraw.sqf
> +	private _targIcon = format [_targetType, _targetModifier];
What were you trying to fix?
This breaks highlighting the selected target and different colours for PFZ colours. 

> fcr/tds icon sorter didn't work and leaves them at default 

I am assuming this is that, we can work on a solution to it together if you want?

2020-10-26 22:33 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdRTSDDraw.sqf
> +		private _targIcon = format [_targetType, _targetModifier];
See above comment on `fn_mpdRFCRDraw.sqf`

2020-10-28 22:13 UTC, SachaOropeza commented
Are those ready for merge @mattysmith22 ? 🤔😉

2020-10-28 22:14 UTC, SachaOropeza commented
@Ollieollieolllie Please be more explicit on your commit titles & description. I'm getting lost. 😅

2020-10-30 08:32 UTC, mattysmith22 commented
I don't know, haven't had time to fix. I'm quite busy today and tomorrow, I may have time Sunday though!

I agree with Sacha though, commit messages are amazing to work out what you intended to change and allows us to compare that to what has been changed. "Fix" unfortunately isn't descriptive enough.

@SachaOropeza I would recommend [squashing when you merge this commit](https://github.blog/2016-04-01-squash-your-commits/) to keep history clean and descriptive

2020-10-30 09:28 UTC, mattysmith22 reviewed
Much better, it is looking a lot cleaner!

I am not explicitly approving yet because I want to do some actual checks in-game before I say that it is fine but just a read through of the code shows significant improvements! Your commit messages since Sacha's comment are also much better.

2020-10-30 09:28 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdRFCRDraw.sqf
> +	private _targicon = "gen";
Out of curiosity, what was the thought process behind changing this name here? I thought `_targetType` was more descriptive in what is being stored and keeps the same variable name as in `fza_fnc_mpdRTSDDraw`. `_targicon` is also not in camel case and collides with another use of `_targIcon` below which while not really mattering could cause confusion for other readers.

If there is a reason though, that's fine!

2020-10-30 09:28 UTC, mattysmith22 commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/targeting/fn_targetingUpdate.sqf
> +//Disabling this line below fixes the ASe page & The contents below are already beign done on page_ase
I'm going to do some testing of my own in-game

2020-11-05 01:27 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/ecm/CMSmk2.sqf
>  if (!(isNil "fza_ah64_noscripts") || !(isengineon _ac) || !(alive _ac) || !(_munition isKindOf "MissileBase") || !(player in _ac)) exitwith {};
SORTED

2020-11-05 01:27 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/fcr_longbow.sqf
>  if (isNil "fza_ah64_ada_units") then {
SORTED

2020-11-05 01:27 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/ihadss/fn_ihadssDraw.sqf
> +//auto hover detector//
SORTED

2020-11-05 01:27 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/ecm/CMSmk2.sqf
> +/*5 / 2 => 2
SORTED

2020-11-05 01:27 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/ecm/CMSmk2.sqf
> +		_reldir = ((getposasl _ac select 0) - (getposasl _missile select 0)) atan2 ((getposasl _ac select 1) - (getposasl _missile select 1));
SORTED

2020-11-05 01:27 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/ecm/CMSmk2.sqf
> +_spoken = 1;
SORTED

2020-11-05 01:28 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/ecm/CMSmk2.sqf
> +_spoken = 1;
This was from when I thought the script is self was rerunning

2020-11-05 01:28 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/ecm/CMSmk2.sqf
> +if (_read == 1 && _range < 8000) then
SORTED

2020-11-05 01:28 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdRFCRDraw.sqf
> +	private _targIcon = format [_targetType, _targetModifier];
Fixed

2020-11-05 01:28 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdRTSDDraw.sqf
> +		private _targIcon = format [_targetType, _targetModifier];
fixed

2020-11-05 01:29 UTC, Ollieollieolllie commented on @AH-64D Apache Longbow/Addons/fza_ah64_controls/scripting/functions/mpd/fn_mpdRFCRDraw.sqf
> +	private _targicon = "gen";
Changed

2020-11-06 15:07 UTC, merged